export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  INCIDENT_DECLARED = 'INCIDENT_DECLARED',
  TEST_SCHEDULED = 'TEST_SCHEDULED',
  POLICY_UPDATE = 'POLICY_UPDATE',
  RISK_ESCALATED = 'RISK_ESCALATED',
  TRAINING_REMINDER = 'TRAINING_REMINDER',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  WORKFLOW_UPDATE = 'WORKFLOW_UPDATE',
  WORKFLOW_ASSIGNED = 'WORKFLOW_ASSIGNED',
  WORKFLOW_APPROVED = 'WORKFLOW_APPROVED',
  WORKFLOW_REJECTED = 'WORKFLOW_REJECTED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  RISK_IDENTIFIED = 'RISK_IDENTIFIED',
  COMPLIANCE_AUDIT_DUE = 'COMPLIANCE_AUDIT_DUE',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  ARCHIVED = 'ARCHIVED',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
}
