export { default as LoginPage } from './LoginPage.vue'
export { default as RegisterPage } from './RegisterPage.vue'
export { default as ForgotPasswordPage } from './ForgotPasswordPage.vue'
export { default as ResetPasswordPage } from './ResetPasswordPage.vue'
export { default as VerifyEmailPage } from './VerifyEmailPage.vue'
export { default as ErrorNotFoundPage } from './ErrorNotFoundPage.vue'