export enum IncidentSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFORMATIONAL = 'INFORMATIONAL',
}

export enum EscalationLevel {
  NO_ESCALATION = 'NO_ESCALATION',
  LEVEL_1_SUPERVISOR = 'LEVEL_1_SUPERVISOR',
  LEVEL_2_DEPARTMENT_HEAD = 'LEVEL_2_DEPARTMENT_HEAD',
  LEVEL_3_BUSINESS_UNIT_MANAGER = 'LEVEL_3_BUSINESS_UNIT_MANAGER',
  LEVEL_4_EXECUTIVE_DIRECTOR = 'LEVEL_4_EXECUTIVE_DIRECTOR',
  LEVEL_5_BOARD = 'LEVEL_5_BOARD',
  CRITICAL = 'CRITICAL',
}

export enum EscalationStatus {
  NOT_ESCALATED = 'NOT_ESCALATED',
  IN_PROGRESS = 'IN_PROGRESS',
  ESCALATED = 'ESCALATED',
  RESOLVED = 'RESOLVED',
  DECLINED = 'DECLINED',
}
