export enum FeatureToggleType {
  RELEASE = 'RELEASE',
  EXPERIMENT = 'EXPERIMENT',
  OPERATIONAL = 'OPERATIONAL',
  PERMISSION = 'PERMISSION',
  KILL_SWITCH = 'KILL_SWITCH',
}

export enum FeatureToggleStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
  SCHEDULED = 'SCHEDULED',
}

export enum ToggleEnvironment {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
  TESTING = 'TESTING',
}

export enum TargetingType {
  USER_ID = 'USER_ID',
  ORGANISATION_ID = 'ORGANISATION_ID',
  ROLE = 'ROLE',
  PERCENTAGE = 'PERCENTAGE',
  CUSTOM = 'CUSTOM',
  ALL_USERS = 'ALL_USERS',
  CUSTOM_RULE = 'CUSTOM_RULE',
}
