export enum SyncStatus {
  PENDING = 'PENDING',
  SYNCED = 'SYNCED',
  CONFLICT = 'CONFLICT',
}

export enum PendingChangeStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ConflictType {
  UPDATE_UPDATE = 'UPDATE_UPDATE',
  DELETE_UPDATE = 'DELETE_UPDATE',
  UPDATE_DELETE = 'UPDATE_DELETE',
  CREATE_CREATE = 'CREATE_CREATE',
  UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT',
  VERSION_SKEW = 'VERSION_SKEW',
  SCHEMA_CONFLICT = 'SCHEMA_CONFLICT',
  DEPENDENCY_CONFLICT = 'DEPENDENCY_CONFLICT',
  PERMISSION_CONFLICT = 'PERMISSION_CONFLICT',
  VALIDATION_CONFLICT = 'VALIDATION_CONFLICT',
  REFERENCE_CONFLICT = 'REFERENCE_CONFLICT',
  DATA_TYPE_CONFLICT = 'DATA_TYPE_CONFLICT',
  REQUIRED_FIELD_CONFLICT = 'REQUIRED_FIELD_CONFLICT',
  BUSINESS_RULE_CONFLICT = 'BUSINESS_RULE_CONFLICT',
  CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION',
  NETWORK_CONFLICT = 'NETWORK_CONFLICT',
  CUSTOM = 'CUSTOM',
}

export enum ResolutionStrategy {
  CLIENT_WINS = 'CLIENT_WINS',
  SERVER_WINS = 'SERVER_WINS',
  LATEST_WINS = 'LATEST_WINS',
  HIGHER_VERSION_WINS = 'HIGHER_VERSION_WINS',
  MERGE = 'MERGE',
  MANUAL = 'MANUAL',
  AUTO_RESOLVED = 'AUTO_RESOLVED',
  CUSTOM = 'CUSTOM',
  SKIP = 'SKIP',
  NEW_VERSION = 'NEW_VERSION',
}

export enum SyncPriority {
  HIGHEST = 1,
  HIGH = 2,
  MEDIUM = 3,
  LOW = 4,
}
