export enum WorkflowType {
  POLICY_APPROVAL = 'POLICY_APPROVAL',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  BIA_REVIEW = 'BIA_REVIEW',
  BCP_APPROVAL = 'BCP_APPROVAL',
  STRATEGY_APPROVAL = 'STRATEGY_APPROVAL',
  TEST_REVIEW = 'TEST_REVIEW',
  INCIDENT_MANAGEMENT = 'INCIDENT_MANAGEMENT',
  IMPROVEMENT_TRACKING = 'IMPROVEMENT_TRACKING',
  TRAINING_ATTESTATION = 'TRAINING_ATTESTATION',
  COMPLIANCE_REVIEW = 'COMPLIANCE_REVIEW',
  INCIDENT_RESPONSE = 'INCIDENT_RESPONSE',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  COMPLIANCE_AUDIT = 'COMPLIANCE_AUDIT',
}

export enum WorkflowState {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  AWAITING_INPUT = 'AWAITING_INPUT',
  PARALLEL_REVIEW = 'PARALLEL_REVIEW',
  ESCALATED = 'ESCALATED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum WorkflowPriority {
  CRITICAL = 1,
  HIGH = 2,
  MEDIUM = 3,
  LOW = 4,
  BACKGROUND = 5,
}
