export enum BCMPlanStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum RecoveryStrategyType {
  HOT_SITE = 'HotSite',
  COLD_SITE = 'ColdSite',
  CLOUD_FAILOVER = 'CloudFailover',
  MANUAL_WORKAROUND = 'ManualWorkaround',
  HYBRID = 'Hybrid',
  MUTUAL_AGREEMENT = 'MutualAgreement',
}

export enum ExerciseTestType {
  TABLETOP = 'TABLETOP',
  WALKTHROUGH = 'WALKTHROUGH',
  FULL = 'FULL',
  TECHNICAL = 'TECHNICAL',
  FULL_SCALE = 'FULL_SCALE',
  SIMULATION = 'SIMULATION',
}

export enum ReputationalImpact {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RecoveryPriority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum BCMLifecyclePhase {
  INITIATION_GOVERNANCE = 'INITIATION_GOVERNANCE',
  EMBEDDING = 'EMBEDDING',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  BUSINESS_IMPACT_ANALYSIS = 'BUSINESS_IMPACT_ANALYSIS',
  STRATEGY_DESIGN = 'STRATEGY_DESIGN',
  PLAN_GENERATION = 'PLAN_GENERATION',
  APPROVAL_WORKFLOWS = 'APPROVAL_WORKFLOWS',
  TESTING_VALIDATION = 'TESTING_VALIDATION',
  CONTINUOUS_IMPROVEMENT = 'CONTINUOUS_IMPROVEMENT',
}
