export enum RuleType {
  VALIDATION = 'VALIDATION',
  NOTIFICATION = 'NOTIFICATION',
  APPROVAL = 'APPROVAL',
  ESCALATION = 'ESCALATION',
  COMPLIANCE = 'COMPLIANCE',
  RISK_CALCULATION = 'RISK_CALCULATION',
  BCM_AUTOMATION = 'BCM_AUTOMATION',
  DOCUMENT_LIFECYCLE = 'DOCUMENT_LIFECYCLE',
  WORKFLOW_AUTOMATION = 'WORKFLOW_AUTOMATION',
  SYNC_VALIDATION = 'SYNC_VALIDATION',
  ACCESS_CONTROL = 'ACCESS_CONTROL',
  DATA_RETENTION = 'DATA_RETENTION',
  CUSTOM = 'CUSTOM',
  ALERT = 'ALERT',
  AUTOMATION = 'AUTOMATION',
  REMINDER = 'REMINDER',
  SCHEDULED = 'SCHEDULED',
}

export enum RuleTrigger {
  ON_CREATE = 'ON_CREATE',
  ON_UPDATE = 'ON_UPDATE',
  ON_DELETE = 'ON_DELETE',
  ON_STATUS_CHANGE = 'ON_STATUS_CHANGE',
  ON_SCHEDULE = 'ON_SCHEDULE',
  ON_THRESHOLD_BREACH = 'ON_THRESHOLD_BREACH',
  ON_APPROVAL = 'ON_APPROVAL',
  ON_REJECTION = 'ON_REJECTION',
  ON_ESCALATION = 'ON_ESCALATION',
  ON_SYNC = 'ON_SYNC',
  ON_MANUAL = 'ON_MANUAL',
  ON_SAVE = 'ON_SAVE',
  SCHEDULED = 'SCHEDULED',
  ENTITY_CREATED = 'ENTITY_CREATED',
  TIME_BASED = 'TIME_BASED',
  ENTITY_UPDATED = 'ENTITY_UPDATED',
}

export enum RuleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT',
  TESTING = 'TESTING',
  ARCHIVED = 'ARCHIVED',
  DEPRECATED = 'DEPRECATED',
}

export enum RulePriority {
  LOW = 1,
  MEDIUM = 2,
  HIGH = 3,
  CRITICAL = 4,
}

export enum LogicalOperator {
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT',
}

export enum ComparisonOperator {
  EQUALS = 'EQUALS',
  NOT_EQUALS = 'NOT_EQUALS',
  GREATER_THAN = 'GREATER_THAN',
  LESS_THAN = 'LESS_THAN',
  GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
  LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',
  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  IN = 'IN',
  NOT_IN = 'NOT_IN',
  BETWEEN = 'BETWEEN',
  EXISTS = 'EXISTS',
  MATCHES_REGEX = 'MATCHES_REGEX',
}
