export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '/api/v1'

export const API_TIMEOUT = 30000
export const API_RETRY_COUNT = 3
export const API_RETRY_DELAY = 1000

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT: 'RATE_LIMIT',
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  OFFLINE_MODE: 'OFFLINE_MODE',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
} as const

export const STORAGE_KEYS = {
  AUTH_TOKEN: 'auth_token',
  REFRESH_TOKEN: 'refresh_token',
  USER_DATA: 'user_data',
  SETTINGS: 'settings',
  THEME: 'theme',
  LANGUAGE: 'language',
  LAST_SYNC: 'last_sync',
  OFFLINE_QUEUE: 'offline_queue',
  DEVICE_ID: 'device_id',
  ONBOARDING_COMPLETED: 'onboarding_completed',
  PUSH_TOKEN: 'push_token',
} as const

export const FILE_CONSTRAINTS = {
  MAX_SIZE_MB: 50,
  MAX_SIZE_BYTES: 50 * 1024 * 1024,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  ALLOWED_DOCUMENT_TYPES: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain',
    'text/csv',
  ],
  ALLOWED_EXTENSIONS: [
    '.pdf',
    '.doc',
    '.docx',
    '.xls',
    '.xlsx',
    '.ppt',
    '.pptx',
    '.jpg',
    '.jpeg',
    '.png',
    '.gif',
    '.webp',
    '.txt',
    '.csv',
  ],
} as const

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
  LIMIT_OPTIONS: [10, 20, 50, 100],
} as const

export const DATE_FORMATS = {
  DISPLAY: 'MMM dd, yyyy',
  DISPLAY_WITH_TIME: 'MMM dd, yyyy HH:mm',
  API: 'yyyy-MM-dd',
  API_WITH_TIME: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
  TIME: 'HH:mm',
  TIME_12H: 'hh:mm A',
  SHORT: 'dd/MM/yyyy',
  LONG: 'dd MMMM yyyy',
} as const

export const API_ENDPOINTS = {
  // API (general)
  API: {
    PING: '/api/ping',
    VERSION: '/api/version',
    SEARCH: '/api/search',
    SERVER_TIME: '/api/server-time',
    HEALTH: '/api/health',
  },

  // Auth
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
    REFRESH: '/auth/refresh',
    VALIDATE: '/auth/validate',
    PROFILE: '/auth/profile',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    SESSIONS: '/auth/sessions',
    SESSION: (id: string) => `/auth/sessions/${id}`,
    REVOKE_OTHERS: '/auth/sessions/revoke-others',
    CLEANUP: '/auth/cleanup',
    VERIFY_RESET_TOKEN: (token: string) => `/auth/verify-reset-token/${token}`,
  },
  AUTH_TOKENS: {
    BY_USER: (userId: string) => `/auth/tokens/user/${userId}`,
    REVOKE: (tokenId: string) => `/auth/tokens/${tokenId}/revoke`,
    REVOKE_ALL: (userId: string) => `/auth/tokens/user/${userId}/revoke-all`,
  },
  USERS: {
    GET: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
    LIST: '/users',
  },

  // Tenants
  TENANTS: {
    BASE: '/tenants',
    STATISTICS: '/tenants/statistics',
    BY_DOMAIN: (domainPrefix: string) => `/tenants/domain/${domainPrefix}`,
    METRICS: (uuid: string) => `/tenants/${uuid}/metrics`,
    BY_ID: (uuid: string) => `/tenants/${uuid}`,
    UPDATE: (uuid: string) => `/tenants/${uuid}`,
    UPDATE_STATUS: (uuid: string) => `/tenants/${uuid}/status`,
    DELETE: (uuid: string) => `/tenants/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/tenants/${uuid}/permanent`,
    RESTORE: (uuid: string) => `/tenants/${uuid}/restore`,
    AUDIT_LOGS: (tenantId: string) => `/tenants/${tenantId}/audit-logs`,
    AUDIT_SUMMARY: (tenantId: string) => `/tenants/${tenantId}/audit-logs/summary`,
    AUDIT_BY_ACTION: (tenantId: string, action: string) =>
      `/tenants/${tenantId}/audit-logs/actions/${action}`,
    AUDIT_TIMELINE: (tenantId: string) => `/tenants/${tenantId}/audit-logs/timeline`,
  },

  // Organisations
  ORGANISATIONS: {
    BASE: '/organisations',
    STATISTICS: '/organisations/statistics',
    BY_TENANT: (tenantId: string) => `/organisations/tenant/${tenantId}`,
    BY_INDUSTRY: (industryType: string) => `/organisations/industry/${industryType}`,
    BY_ID: (uuid: string) => `/organisations/${uuid}`,
    UPDATE: (uuid: string) => `/organisations/${uuid}`,
    DELETE: (uuid: string) => `/organisations/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/organisations/${uuid}/permanent`,
    RESTORE: (uuid: string) => `/organisations/${uuid}/restore`,
    DASHBOARD: (organisationId: string) => `/organisations/${organisationId}/dashboard`,
    HIERARCHY: (organisationId: string) => `/organisations/${organisationId}/hierarchy`,
    TREE: (organisationId: string) => `/organisations/${organisationId}/tree`,
    VALIDATE_NAME: '/organisations/validate-name',
    INDUSTRY_TYPES: '/organisations/industry-types',
    MATURITY_SCORES: '/organisations/maturity-scores',
    BULK_IMPORT: '/organisations/bulk-import',
    EXPORT: '/organisations/export',
  },

  // Business Units
  BUSINESS_UNITS: {
    BASE: '/business-units',
    STATISTICS: '/business-units/statistics',
    BY_ORGANISATION: (organisationId: string) => `/business-units/organisation/${organisationId}`,
    BY_ID: (uuid: string) => `/business-units/${uuid}`,
    UPDATE: (uuid: string) => `/business-units/${uuid}`,
    DELETE: (uuid: string) => `/business-units/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/business-units/${uuid}/permanent`,
    RESTORE: (uuid: string) => `/business-units/${uuid}/restore`,
    CRITICAL: (organisationId: string) => `/business-units/${organisationId}/critical`,
    CRITICALITY_SCORES: '/business-units/criticality-scores',
    BULK_IMPORT: (organisationId: string) => `/business-units/${organisationId}/bulk-import`,
    EXPORT: (organisationId: string) => `/business-units/${organisationId}/export`,
    HIERARCHY: (businessUnitId: string) => `/business-units/${businessUnitId}/hierarchy`,
    ORGANISATION_HIERARCHY: (organisationId: string) =>
      `/business-units/organisation/${organisationId}/hierarchy`,
    VALIDATE_NAME: '/business-units/validate-name',
  },

  // Departments
  DEPARTMENTS: {
    BASE: '/departments',
    SEARCH: '/departments/search',
    STATISTICS: '/departments/statistics',
    BY_BUSINESS_UNIT: (businessUnitId: string) => `/departments/business-unit/${businessUnitId}`,
    TREE: (businessUnitId: string) => `/departments/${businessUnitId}/tree`,
    REORDER: '/departments/reorder',
    BY_ID: (uuid: string) => `/departments/${uuid}`,
    UPDATE: (uuid: string) => `/departments/${uuid}`,
    DELETE: (uuid: string) => `/departments/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/departments/${uuid}/permanent`,
    RESTORE: (uuid: string) => `/departments/${uuid}/restore`,
    WITHOUT_BIA: (organisationId: string) => `/departments/${organisationId}/without-bia`,
    HIERARCHY: (businessUnitId: string) => `/departments/${businessUnitId}/hierarchy`,
    PATH: (departmentId: string) => `/departments/${departmentId}/path`,
    MOVE: (departmentId: string) => `/departments/${departmentId}/move`,
    VALIDATE_NAME: '/departments/validate-name',
    BULK_IMPORT: (businessUnitId: string) => `/departments/${businessUnitId}/bulk-import`,
    EXPORT: (businessUnitId: string) => `/departments/${businessUnitId}/export`,
  },

  // Critical Functions
  CRITICAL_FUNCTIONS: {
    BASE: '/bcm/critical-functions',
    SUMMARY: '/bcm/critical-functions/summary',
    REQUIRES_BCP: '/bcm/critical-functions/requires-bcp',
    PRIORITY_SUMMARY: '/bcm/critical-functions/priority-summary',
    BY_DEPARTMENT: (departmentId: string) => `/bcm/critical-functions/department/${departmentId}`,
    BY_PRIORITY: (priority: string) => `/bcm/critical-functions/priority/${priority}`,
    BY_ID: (uuid: string) => `/bcm/critical-functions/${uuid}`,
    UPDATE: (uuid: string) => `/bcm/critical-functions/${uuid}`,
    DELETE: (uuid: string) => `/bcm/critical-functions/${uuid}`,
  },

  // BIA
  BIA: {
    BASE: '/bcm/impact-assessments',
    FINANCIAL_SUMMARY: '/bcm/impact-assessments/financial-summary',
    HIGH_IMPACT: '/bcm/impact-assessments/high-impact',
    BY_FUNCTION: (functionId: string) => `/bcm/impact-assessments/function/${functionId}`,
    BY_ID: (uuid: string) => `/bcm/impact-assessments/${uuid}`,
    UPDATE: (uuid: string) => `/bcm/impact-assessments/${uuid}`,
    DELETE: (uuid: string) => `/bcm/impact-assessments/${uuid}`,
    ANALYZE: '/bcm/impact-assessments/analyze',
    EXPORT: (organisationId: string) => `/bcm/impact-assessments/export/${organisationId}`,
  },

  // BCP
  BCP: {
    BASE: '/bcm/plans',
    ACTIVE: '/bcm/plans/active',
    DUE_FOR_REVIEW: '/bcm/plans/due-for-review',
    STATISTICS: '/bcm/plans/statistics',
    BY_FUNCTION: (functionId: string) => `/bcm/plans/function/${functionId}`,
    BY_ID: (uuid: string) => `/bcm/plans/${uuid}`,
    UPDATE: (uuid: string) => `/bcm/plans/${uuid}`,
    APPROVE: (uuid: string) => `/bcm/plans/${uuid}/approve`,
    ARCHIVE: (uuid: string) => `/bcm/plans/${uuid}/archive`,
    ACTIVATE: (uuid: string) => `/bcm/plans/${uuid}/activate`,
    DELETE: (uuid: string) => `/bcm/plans/${uuid}`,
    VALIDATE: '/bcm/plans/validate',
    PROGRESS: '/bcm/plans/progress',
    EXPORT: (id: string) => `/bcm/plans/${id}/export`,
  },

  // Recovery Strategies
  RECOVERY_STRATEGIES: {
    BASE: '/bcm/recovery-strategies',
    HIGH_SUCCESS_RATE: '/bcm/recovery-strategies/high-success-rate',
    STATISTICS: '/bcm/recovery-strategies/statistics',
    BY_PLAN: (planId: string) => `/bcm/recovery-strategies/plan/${planId}`,
    BY_TYPE: (type: string) => `/bcm/recovery-strategies/type/${type}`,
    BY_ID: (uuid: string) => `/bcm/recovery-strategies/${uuid}`,
    UPDATE: (uuid: string) => `/bcm/recovery-strategies/${uuid}`,
    DELETE: (uuid: string) => `/bcm/recovery-strategies/${uuid}`,
    COMPARE: (bcpId: string) => `/bcm/recovery-strategies/${bcpId}/compare`,
  },

  // Exercise Tests
  EXERCISE_TESTS: {
    BASE: '/exercise-tests',
    PASSED: '/exercise-tests/passed',
    FAILED: '/exercise-tests/failed',
    UPCOMING: '/exercise-tests/upcoming',
    PAST: '/exercise-tests/past',
    DATE_RANGE: '/exercise-tests/date-range',
    BY_BCP: (bcpId: string) => `/exercise-tests/bcp/${bcpId}`,
    BY_ID: (uuid: string) => `/exercise-tests/${uuid}`,
    UPDATE: (uuid: string) => `/exercise-tests/${uuid}`,
    RECORD_RESULT: (uuid: string) => `/exercise-tests/${uuid}/record-result`,
    DELETE: (uuid: string) => `/exercise-tests/${uuid}`,
    STATISTICS: '/bcm/exercise-tests/statistics',
  },

  // Risks
  RISKS: {
    BASE: '/risks',
    STATISTICS: '/risks/statistics',
    HIGH: '/risks/high',
    MY_ASSIGNED: '/risks/my-assigned',
    OVERDUE_REVIEWS: '/risks/overdue-reviews',
    MATRIX: (organisationId: string) => `/risks/${organisationId}/matrix`,
    HEATMAP: (organisationId: string) => `/risks/${organisationId}/heatmap`,
    HEATMAP_SUMMARY: (organisationId: string) => `/risks/${organisationId}/heatmap-summary`,
    TRENDS: (organisationId: string) => `/risks/${organisationId}/trends`,
    TREND_ANALYSIS: (organisationId: string) => `/risks/${organisationId}/trend-analysis`,
    BY_ID: (uuid: string) => `/risks/${uuid}`,
    UPDATE: (uuid: string) => `/risks/${uuid}`,
    ASSESS: (uuid: string) => `/risks/${uuid}/assess`,
    APPROVE: (uuid: string) => `/risks/${uuid}/approve`,
    ASSIGN: (uuid: string) => `/risks/${uuid}/assign`,
    CLOSE: (uuid: string) => `/risks/${uuid}/close`,
    DELETE: (uuid: string) => `/risks/${uuid}`,
    MITIGATION_PLAN: (riskId: string) => `/risks/${riskId}/mitigation-plan`,
    MITIGATION_ACTION: (riskId: string, actionId: string) =>
      `/risks/${riskId}/mitigation-plan/actions/${actionId}`,
    BULK_UPDATE_STATUS: '/risks/bulk-update-status',
    BULK_ASSIGN: '/risks/bulk-assign',
    BULK_DELETE: '/risks/bulk-delete',
    EXPORT: (organisationId: string) => `/risks/export/${organisationId}`,
  },

  // Incidents
  INCIDENTS: {
    BASE: '/incidents',
    ACTIVE: '/incidents/active',
    CLOSED: '/incidents/closed',
    CRITICAL: '/incidents/critical',
    DATE_RANGE: '/incidents/date-range',
    BY_ORGANISATION: (organisationId: string) => `/incidents/organisation/${organisationId}`,
    BY_SEVERITY: (severity: string) => `/incidents/severity/${severity}`,
    BY_BCP: (bcpId: string) => `/incidents/bcp/${bcpId}`,
    BY_ID: (uuid: string) => `/incidents/${uuid}`,
    UPDATE: (uuid: string) => `/incidents/${uuid}`,
    CLOSE: (uuid: string) => `/incidents/${uuid}/close`,
    REOPEN: (uuid: string) => `/incidents/${uuid}/reopen`,
    ESCALATE: (uuid: string) => `/incidents/${uuid}/escalate`,
    ASSIGN: (uuid: string) => `/incidents/${uuid}/assign`,
    ADD_UPDATE: (uuid: string) => `/incidents/${uuid}/updates`,
    DELETE: (uuid: string) => `/incidents/${uuid}`,
    STATS: '/incidents/stats',
    RESPONSE_PLAN: (incidentId: string) => `/incidents/${incidentId}/response-plan`,
    ACTIVATE_PLAN: (incidentId: string) => `/incidents/${incidentId}/activate-plan`,
    RESPONSE_ACTION: (incidentId: string, actionId: string) =>
      `/incidents/${incidentId}/response-plan/actions/${actionId}`,
    RECOVERY_METRICS: (incidentId: string) => `/incidents/${incidentId}/recovery-metrics`,
    REPORT: (incidentId: string, reportType: string) =>
      `/incidents/${incidentId}/report/${reportType}`,
    TIMELINE: (incidentId: string) => `/incidents/${incidentId}/timeline`,
    EXPORT: (organisationId: string) => `/incidents/export/${organisationId}`,
  },

  // Compliance
  COMPLIANCE: {
    BASE: '/compliance',
    SUMMARY: '/compliance/summary',
    OVERDUE: '/compliance/overdue',
    UPCOMING: '/compliance/upcoming',
    BY_ORGANISATION: (organisationId: string) => `/compliance/organisation/${organisationId}`,
    BY_STANDARD: (standard: string) => `/compliance/standard/${standard}`,
    BY_STATUS: (status: string) => `/compliance/status/${status}`,
    BY_ID: (uuid: string) => `/compliance/${uuid}`,
    UPDATE: (uuid: string) => `/compliance/${uuid}`,
    UPDATE_STATUS: (uuid: string) => `/compliance/${uuid}/status`,
    DELETE: (uuid: string) => `/compliance/${uuid}`,
    EVIDENCE: (id: string) => `/compliance/${id}/evidence`,
    REMOVE_EVIDENCE: (id: string, index: number) => `/compliance/${id}/evidence/${index}`,
    GAPS: '/compliance/gaps',
    EXPORT: '/compliance/export',
    AUDIT_HISTORY: (id: string) => `/compliance/${id}/audit-history`,
    SCHEDULE_AUDIT: (id: string) => `/compliance/${id}/schedule-audit`,
    BULK_UPDATE_STATUS: '/compliance/bulk-update-status',
    VERIFY: '/compliance/verify',
    GENERATE_REPORT: '/compliance/generate-report',
  },

  // Workflows
  WORKFLOWS: {
    BASE: '/workflows',
    STATS: '/workflows/stats',
    METRICS: '/workflows/metrics',
    PENDING_APPROVALS: '/workflows/pending/approvals',
    OVERDUE: '/workflows/status/overdue',
    ACTIVE: '/workflows/status/active',
    ESCALATED: '/workflows/status/escalated',
    BY_TYPE: (workflowType: string) => `/workflows/type/${workflowType}`,
    BY_STATE: (workflowState: string) => `/workflows/state/${workflowState}`,
    BY_INITIATED_BY: (userId: string) => `/workflows/initiated-by/${userId}`,
    BY_ASSIGNED_TO: (userId: string) => `/workflows/assigned-to/${userId}`,
    BY_ID: (uuid: string) => `/workflows/${uuid}`,
    UPDATE: (uuid: string) => `/workflows/${uuid}`,
    DELETE: (uuid: string) => `/workflows/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/workflows/${uuid}/permanent`,
    RESTORE: (uuid: string) => `/workflows/${uuid}/restore`,
    SUBMIT: (uuid: string) => `/workflows/${uuid}/submit`,
    START_REVIEW: (uuid: string) => `/workflows/${uuid}/start-review`,
    APPROVE: (uuid: string) => `/workflows/${uuid}/approve`,
    REJECT: (uuid: string) => `/workflows/${uuid}/reject`,
    COMPLETE: (uuid: string) => `/workflows/${uuid}/complete`,
    ADD_COMMENT: (uuid: string) => `/workflows/${uuid}/comment`,
    ESCALATE: (uuid: string) => `/workflows/${uuid}/escalate`,
    REASSIGN: (uuid: string) => `/workflows/${uuid}/reassign`,
    ARCHIVE: (uuid: string) => `/workflows/${uuid}/archive`,
    CANCEL: (uuid: string) => `/workflows/${uuid}/cancel`,
    APPROVAL_CHAIN: (workflowId: string) => `/workflows/${workflowId}/approval-chain`,
    COMMENTS: (workflowId: string) => `/workflows/${workflowId}/comments`,
    TEMPLATES: '/workflows/templates',
    TEMPLATE_BY_ID: (id: string) => `/workflows/templates/${id}`,
    CREATE_FROM_TEMPLATE: (templateId: string) => `/workflows/templates/${templateId}/create`,
    EXPORT: '/workflows/export',
    BULK_APPROVE: '/workflows/bulk-approve',
    BULK_REJECT: '/workflows/bulk-reject',
    BULK_REASSIGN: '/workflows/bulk-reassign',
  },

  // Documents
  DOCUMENTS: {
    BASE: '/documents',
    UPLOAD: '/documents/upload',
    SEARCH: '/documents/search',
    STATS: '/documents/stats',
    PENDING_APPROVALS: '/documents/pending-approvals',
    APPROVED: '/documents/approved',
    EXPIRED: '/documents/expired',
    BY_TYPE: (documentType: string) => `/documents/type/${documentType}`,
    BY_STATUS: (status: string) => `/documents/status/${status}`,
    BY_ORGANISATION: (organisationId: string) => `/documents/organisation/${organisationId}`,
    DOWNLOAD: (uuid: string) => `/documents/${uuid}/download`,
    PREVIEW: (uuid: string) => `/documents/${uuid}/preview`,
    VERSIONS: (uuid: string) => `/documents/${uuid}/versions`,
    RESTORE_VERSION: (uuid: string) => `/documents/${uuid}/restore-version`,
    BY_ID: (uuid: string) => `/documents/${uuid}`,
    UPDATE: (uuid: string) => `/documents/${uuid}`,
    NEW_VERSION: (uuid: string) => `/documents/${uuid}/new-version`,
    SUBMIT_REVIEW: (uuid: string) => `/documents/${uuid}/submit-review`,
    APPROVE: (uuid: string) => `/documents/${uuid}/approve`,
    REJECT: (uuid: string) => `/documents/${uuid}/reject`,
    ARCHIVE: (uuid: string) => `/documents/${uuid}/archive`,
    PUBLISH: (uuid: string) => `/documents/${uuid}/publish`,
    DELETE: (uuid: string) => `/documents/${uuid}`,
    VERIFY: (uuid: string) => `/documents/${uuid}/verify`,
    TAGS: (uuid: string) => `/documents/${uuid}/tags`,
    BULK_DOWNLOAD: '/documents/bulk-download',
    BULK_OPERATION: '/documents/bulk-operation',
    TEMPLATES: '/documents/templates',
    GENERATE_FROM_TEMPLATE: '/documents/generate-from-template',
  },

  // Notifications
  NOTIFICATIONS: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread/count',
    COUNTS: '/notifications/counts',
    MARK_ALL_READ: '/notifications/mark-all-read',
    PREFERENCES: '/notifications/preferences',
    TEMPLATES: '/notifications/templates',
    BULK: '/notifications/bulk',
    UNREAD: '/notifications/unread',
    BY_STATUS: (status: string) => `/notifications/status/${status}`,
    BY_TYPE: (type: string) => `/notifications/type/${type}`,
    BY_ID: (uuid: string) => `/notifications/${uuid}`,
    MARK_READ: (uuid: string) => `/notifications/${uuid}/read`,
    MARK_UNREAD: (uuid: string) => `/notifications/${uuid}/unread`,
    ARCHIVE: (uuid: string) => `/notifications/${uuid}/archive`,
    DISMISS: (uuid: string) => `/notifications/${uuid}/dismiss`,
    DELETE: (uuid: string) => `/notifications/${uuid}`,
    PERMANENT_DELETE: (uuid: string) => `/notifications/${uuid}/permanent`,
    BULK_DELETE: '/notifications/bulk-delete',
    SETTINGS: (userId: string) => `/notifications/settings/${userId}`,
    TRACK_CLICK: (notificationId: string) => `/notifications/${notificationId}/track-click`,
    SUMMARY: '/notifications/summary',
  },

  // Audit
  AUDIT: {
    BASE: '/audit/logs',
    BY_ID: (uuid: string) => `/audit/logs/${uuid}`,
    ENTITY_HISTORY: (entityType: string, entityId: string) =>
      `/audit/entity-history/${entityType}/${entityId}`,
    USER_ACTIVITY: (userId: string) => `/audit/user-activity/${userId}`,
    MY_ACTIVITY: '/audit/my-activity',
    STATS: '/audit/stats',
    SUMMARY: '/audit/summary',
    EXPORT: '/audit/export',
    CLEANUP: '/audit/cleanup',
    REPLAY: '/audit/replay',
    ANOMALIES: '/audit/anomalies',
    ANOMALY_BY_ID: (anomalyId: string) => `/audit/anomalies/${anomalyId}`,
    RETENTION_POLICIES: '/audit/retention-policies',
    RETENTION_POLICY_BY_ID: (uuid: string) => `/audit/retention-policies/${uuid}`,
    APPLY_RETENTION: '/audit/apply-retention',
  },

  // Feature Toggles
  FEATURE_TOGGLES: {
    BASE: '/features',
    STATS: '/features/stats',
    EVALUATE: '/features/evaluate',
    BATCH_EVALUATE: '/features/evaluate/batch',
    OVERRIDES: '/features/overrides',
    ACTIVE_OVERRIDES: '/features/overrides/active',
    DELETE_EXPIRED_OVERRIDES: '/features/overrides/expired',
    OVERRIDE_BY_ID: (uuid: string) => `/features/overrides/${uuid}`,
    BY_ID: (uuid: string) => `/features/${uuid}`,
    UPDATE: (uuid: string) => `/features/${uuid}`,
    DELETE: (uuid: string) => `/features/${uuid}`,
    AUDIT_LOGS: (featureToggleId: string) => `/features/${featureToggleId}/audit-logs`,
  },

  // Rules
  RULES: {
    BASE: '/rules',
    STATISTICS: '/rules/statistics',
    ACTIVE: '/rules/active',
    BY_ID: (uuid: string) => `/rules/${uuid}`,
    UPDATE: (uuid: string) => `/rules/${uuid}`,
    ACTIVATE: (uuid: string) => `/rules/${uuid}/activate`,
    DEACTIVATE: (uuid: string) => `/rules/${uuid}/deactivate`,
    ARCHIVE: (uuid: string) => `/rules/${uuid}/archive`,
    EXECUTE: (uuid: string) => `/rules/${uuid}/execute`,
    TEST: (uuid: string) => `/rules/${uuid}/test`,
    DUPLICATE: (uuid: string) => `/rules/${uuid}/duplicate`,
    DELETE: (uuid: string) => `/rules/${uuid}`,
    EXECUTION_LOGS: (ruleId: string) => `/rules/${ruleId}/logs`,
    EXECUTION_STATS: (ruleId: string) => `/rules/${ruleId}/execution-stats`,
    SCHEDULE: (ruleId: string) => `/rules/${ruleId}/schedule`,
    VALIDATE: '/rules/validate',
    BULK_ACTIVATE: '/rules/bulk-activate',
    BULK_DEACTIVATE: '/rules/bulk-deactivate',
    BULK_DELETE: '/rules/bulk-delete',
    EXECUTION_LOGS_CLEANUP: '/rules/execution-logs/cleanup',
  },

  // Sync
  SYNC: {
    BASE: '/sync',
    PULL: '/sync/pull',
    PUSH: '/sync/push',
    BATCH: '/sync/batch',
    STATUS: '/sync/status',
    TRIGGER: '/sync/trigger',
    CONFLICTS_RESOLVE: '/sync/conflicts/resolve',
    PENDING_CHANGES: '/sync/pending-changes',
    PENDING_CHANGES_PENDING: '/sync/pending-changes/pending',
    PENDING_CHANGES_STATS: '/sync/pending-changes/stats',
    PENDING_CHANGES_BY_ENTITY: (entityId: string) => `/sync/pending-changes/entity/${entityId}`,
    PENDING_CHANGES_BY_TYPE: (entityType: string) => `/sync/pending-changes/type/${entityType}`,
    PENDING_CHANGES_BY_ID: (uuid: string) => `/sync/pending-changes/${uuid}`,
    PENDING_CHANGES_RETRY_FAILED: '/sync/pending-changes/retry-failed',
    PENDING_CHANGES_CLEANUP: '/sync/pending-changes/cleanup',
    CONFLICTS: '/sync/conflicts',
    CONFLICTS_UNRESOLVED: '/sync/conflicts/unresolved',
    CONFLICTS_STATS: '/sync/conflicts/stats',
    CONFLICTS_BY_ENTITY: (entityId: string) => `/sync/conflicts/entity/${entityId}`,
    CONFLICT_BY_ID: (uuid: string) => `/sync/conflicts/${uuid}`,
    CONFLICT_RESOLVE: (uuid: string) => `/sync/conflicts/${uuid}/resolve`,
    CONFLICT_PREVIEW: (uuid: string) => `/sync/conflicts/${uuid}/preview`,
    CONFLICT_DELETE: (uuid: string) => `/sync/conflicts/${uuid}`,
    CONFLICTS_CLEANUP: '/sync/conflicts/cleanup',
    METADATA: '/sync/metadata',
    LAST_SYNC_TOKEN: '/sync/metadata/last-sync-token',
    SYNC_PROGRESS: '/sync/metadata/sync-progress',
    METADATA_STATS: '/sync/metadata/stats',
    METADATA_BY_PREFIX: (prefix: string) => `/sync/metadata/prefix/${prefix}`,
    METADATA_BY_KEY: (key: string) => `/sync/metadata/${key}`,
    METADATA_UPDATE: (key: string) => `/sync/metadata/${key}`,
    METADATA_UPDATE_TOKEN: '/sync/metadata/last-sync-token',
    METADATA_INCREMENT: (key: string) => `/sync/metadata/${key}/increment`,
    METADATA_BACKUP: '/sync/metadata/backup',
    METADATA_CLEAR_PREFIX: (prefix: string) => `/sync/metadata/prefix/${prefix}`,
    CONFIG: '/sync/config',
    TOMBSTONES: '/sync/tombstones',
    TOMBSTONES_CLEANUP: '/sync/tombstones/cleanup',
    STATS: '/sync/stats',
  },

  // Cache
  CACHE: {
    BASE: '/cache',
    STATS: '/cache/stats',
    CLEAN_EXPIRED: '/cache/clean-expired',
    CLEAR_ALL: '/cache/clear-all',
    KEYS: '/cache/keys',
    BY_PATTERN: '/cache/pattern',
    BY_TAGS: (tags: string) => `/cache/tags/${tags}`,
    DELETE_BY_TAGS: (tags: string) => `/cache/tags/${tags}`,
    BULK: '/cache/bulk',
    EXISTS: (key: string) => `/cache/${encodeURIComponent(key)}/exists`,
    TTL: (key: string) => `/cache/${encodeURIComponent(key)}/ttl`,
    INCREMENT: (key: string) => `/cache/${encodeURIComponent(key)}/increment`,
    DECREMENT: (key: string) => `/cache/${encodeURIComponent(key)}/decrement`,
    GET_OR_SET: (key: string) => `/cache/${encodeURIComponent(key)}/get-or-set`,
    BY_KEY: (key: string) => `/cache/${encodeURIComponent(key)}`,
    UPDATE: (key: string) => `/cache/${encodeURIComponent(key)}`,
    DELETE: (key: string) => `/cache/${encodeURIComponent(key)}`,
    WARM_UP: '/cache/warm-up',
  },

  // Dashboard
  DASHBOARD: {
    COMPLETE: '/dashboard/complete',
    USER_CONFIG: '/dashboard/user-config',
    CONFIGS: '/dashboard/configs',
    CONFIG_BY_ID: (uuid: string) => `/dashboard/configs/${uuid}`,
    ORGANISATION_CONFIGS: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/configs`,
    ROLE_CONFIGS: (organisationId: string, role: string) =>
      `/dashboard/organisations/${organisationId}/roles/${role}/configs`,
    KPIS: (organisationId: string) => `/dashboard/organisations/${organisationId}/kpis`,
    RISK_SUMMARY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/risk-summary`,
    BCM_SUMMARY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/bcm-summary`,
    INCIDENT_SUMMARY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/incident-summary`,
    COMPLIANCE_SUMMARY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/compliance-summary`,
    WORKFLOW_SUMMARY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/workflow-summary`,
    RECENT_ACTIVITY: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/recent-activity`,
    UPCOMING_TASKS: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/upcoming-tasks`,
    RISK_TRENDS: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/risk-trends`,
    COMPLIANCE_OVERVIEW: (organisationId: string) =>
      `/dashboard/organisations/${organisationId}/compliance-overview`,
  },

  // Reports
  REPORTS: {
    BASE: '/reports',
    PUBLIC: '/reports/public',
    STATS: '/reports/stats',
    BY_TYPE: (reportType: string) => `/reports/type/${reportType}`,
    BY_ORGANISATION: (organisationId: string) => `/reports/organisation/${organisationId}`,
    BY_ID: (uuid: string) => `/reports/${uuid}`,
    UPDATE: (uuid: string) => `/reports/${uuid}`,
    DELETE: (uuid: string) => `/reports/${uuid}`,
    GENERATE: (uuid: string) => `/reports/${uuid}/generate`,
    CANCEL: (uuid: string) => `/reports/${uuid}/cancel`,
    SCHEDULE: (uuid: string) => `/reports/${uuid}/schedule`,
    GET_DATA: (uuid: string) => `/reports/${uuid}/data`,
    DELETE_EXPIRED: '/reports/maintenance/delete-expired',
  },

  // Settings
  SETTINGS: {
    BASE: '/settings',
    BY_ID: (id: string) => `/settings/${id}`,
    USER: (userId: string) => `/settings/user/${userId}`,
    ORGANISATION: (organisationId: string) => `/settings/organisation/${organisationId}`,
    SYSTEM_DEFAULTS: '/settings/system-defaults',
    RESET_USER: (userId: string) => `/settings/user/${userId}/reset`,
    RESET_ORGANISATION: (organisationId: string) =>
      `/settings/organisation/${organisationId}/reset`,
    PREFERENCE: (userId: string, key: string) => `/settings/user/${userId}/preference/${key}`,
    PREFERENCES_BULK: (userId: string) => `/settings/user/${userId}/preferences/bulk`,
    NOTIFICATION_SETTINGS: (userId: string, type: string) =>
      `/settings/user/${userId}/notifications/${type}`,
    NOTIFICATION_SETTINGS_BULK: (userId: string) => `/settings/user/${userId}/notifications/bulk`,
    THEME_SETTINGS: (userId: string) => `/settings/user/${userId}/theme`,
    LANGUAGE_SETTINGS: (userId: string) => `/settings/user/${userId}/language`,
    SECURITY_SETTINGS: (userId: string) => `/settings/user/${userId}/security`,
    SYNC_SETTINGS: (userId: string) => `/settings/user/${userId}/sync`,
    TRIGGER_SYNC: (userId: string) => `/settings/user/${userId}/sync/trigger`,
    TEMPLATES: '/settings/templates',
    APPLY_TEMPLATE: (templateId: string) => `/settings/templates/${templateId}/apply`,
    TWO_FACTOR: (userId: string) => `/settings/user/${userId}/two-factor`,
    TWO_FACTOR_VERIFY: (userId: string) => `/settings/user/${userId}/two-factor/verify`,
    AVAILABLE_THEMES: '/settings/available-themes',
    AVAILABLE_LOCALES: '/settings/available-locales',
    VALIDATE: '/settings/validate',
    EXPORT: '/settings/export',
    IMPORT: '/settings/import',
    BULK_UPDATE: '/settings/bulk-update',
  },

  // BCM Lifecycle
  BCM_LIFECYCLE: {
    BASE: (organisationId: string) => `/bcm/lifecycle/${organisationId}`,
    PROGRESS: (organisationId: string) => `/bcm/lifecycle/${organisationId}/progress`,
    TASK: (organisationId: string, taskId: string) =>
      `/bcm/lifecycle/${organisationId}/tasks/${taskId}`,
  },

  // BCM Metrics
  BCM_METRICS: {
    BASE: '/bcm/metrics',
    DASHBOARD: '/bcm/dashboard',
    MATURITY_ASSESSMENT: '/bcm/maturity-assessment',
  },

  // Cache Extras
  CACHE_EXTRA: {
    KEYS: '/cache/keys',
    TTL: (key: string) => `/cache/${encodeURIComponent(key)}/ttl`,
    INCREMENT: (key: string) => `/cache/${encodeURIComponent(key)}/increment`,
    DECREMENT: (key: string) => `/cache/${encodeURIComponent(key)}/decrement`,
    WARM_UP: '/cache/warm-up',
  },
} as const
