import { EntityType } from '../../shared/enums/system.enum'

export const ENTITY_DISPLAY_NAMES: Record<EntityType, string> = {
  [EntityType.ORGANISATION]: 'Organisation',
  [EntityType.BUSINESS_UNIT]: 'Business Unit',
  [EntityType.DEPARTMENT]: 'Department',
  [EntityType.USER]: 'User',
  [EntityType.CRITICAL_FUNCTION]: 'Critical Function',
  [EntityType.RISK]: 'Risk',
  [EntityType.BUSINESS_IMPACT_ASSESSMENT]: 'Business Impact Assessment',
  [EntityType.BUSINESS_CONTINUITY_PLAN]: 'Business Continuity Plan',
  [EntityType.RECOVERY_STRATEGY]: 'Recovery Strategy',
  [EntityType.INCIDENT]: 'Incident',
  [EntityType.EXERCISE_TEST]: 'Exercise Test',
  [EntityType.AUDIT_LOG]: 'Audit Log',
  [EntityType.COMPLIANCE_RECORD]: 'Compliance Record',
  [EntityType.DOCUMENT]: 'Document',
  [EntityType.NOTIFICATION]: 'Notification',
  [EntityType.WORKFLOW]: 'Workflow',
  [EntityType.TENANT]: 'Tenant',
  [EntityType.RULE]: 'Rule',
  [EntityType.FEATURE_TOGGLE]: 'Feature Toggle',
  [EntityType.REPORT]: 'Report',
  [EntityType.SETTINGS]: 'Settings',
  [EntityType.CACHE]: 'Cache',
  [EntityType.AUTH_TOKEN]: 'Auth Token',
  [EntityType.SYNC_METADATA]: 'Sync Metadata',
  [EntityType.SYNC_CONFLICT]: 'Sync Conflict',
  [EntityType.PENDING_CHANGE]: 'Pending Change',
}

export const ENTITY_ICONS: Record<EntityType, string> = {
  [EntityType.ORGANISATION]: 'business',
  [EntityType.BUSINESS_UNIT]: 'account_tree',
  [EntityType.DEPARTMENT]: 'group',
  [EntityType.USER]: 'person',
  [EntityType.CRITICAL_FUNCTION]: 'settings',
  [EntityType.RISK]: 'warning',
  [EntityType.BUSINESS_IMPACT_ASSESSMENT]: 'assessment',
  [EntityType.BUSINESS_CONTINUITY_PLAN]: 'description',
  [EntityType.RECOVERY_STRATEGY]: 'shield',
  [EntityType.INCIDENT]: 'report_problem',
  [EntityType.EXERCISE_TEST]: 'sports_score',
  [EntityType.AUDIT_LOG]: 'history',
  [EntityType.COMPLIANCE_RECORD]: 'verified',
  [EntityType.DOCUMENT]: 'folder',
  [EntityType.NOTIFICATION]: 'notifications',
  [EntityType.WORKFLOW]: 'account_tree',
  [EntityType.TENANT]: 'domain',
  [EntityType.RULE]: 'rule',
  [EntityType.FEATURE_TOGGLE]: 'toggle_on',
  [EntityType.REPORT]: 'bar_chart',
  [EntityType.SETTINGS]: 'settings',
  [EntityType.CACHE]: 'cached',
  [EntityType.AUTH_TOKEN]: 'vpn_key',
  [EntityType.SYNC_METADATA]: 'sync',
  [EntityType.SYNC_CONFLICT]: 'conflict',
  [EntityType.PENDING_CHANGE]: 'pending',
}

export const ENTITY_ROUTES: Record<EntityType, string> = {
  [EntityType.ORGANISATION]: '/organisations',
  [EntityType.BUSINESS_UNIT]: '/business-units',
  [EntityType.DEPARTMENT]: '/departments',
  [EntityType.USER]: '/users',
  [EntityType.CRITICAL_FUNCTION]: '/bcm/critical-functions',
  [EntityType.RISK]: '/risks',
  [EntityType.BUSINESS_IMPACT_ASSESSMENT]: '/bcm/impact-assessments',
  [EntityType.BUSINESS_CONTINUITY_PLAN]: '/bcm/plans',
  [EntityType.RECOVERY_STRATEGY]: '/bcm/recovery-strategies',
  [EntityType.INCIDENT]: '/incidents',
  [EntityType.EXERCISE_TEST]: '/exercise-tests',
  [EntityType.AUDIT_LOG]: '/audit',
  [EntityType.COMPLIANCE_RECORD]: '/compliance',
  [EntityType.DOCUMENT]: '/documents',
  [EntityType.NOTIFICATION]: '/notifications',
  [EntityType.WORKFLOW]: '/workflows',
  [EntityType.TENANT]: '/tenants',
  [EntityType.RULE]: '/rules',
  [EntityType.FEATURE_TOGGLE]: '/features',
  [EntityType.REPORT]: '/reports',
  [EntityType.SETTINGS]: '/settings',
  [EntityType.CACHE]: '/cache',
  [EntityType.AUTH_TOKEN]: '/auth/tokens',
  [EntityType.SYNC_METADATA]: '/sync/metadata',
  [EntityType.SYNC_CONFLICT]: '/sync/conflicts',
  [EntityType.PENDING_CHANGE]: '/sync/pending-changes',
}
