services:
  vue-capacitor:
    build: .
    container_name: vue-capacitor-env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9811:9812" # Quasar Dev Server
    stdin_open: true
    tty: true