export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING = 'PENDING',
  DELETED = 'DELETED',
  MAINTENANCE = 'MAINTENANCE',
}

export enum TenantTier {
  FREE = 'FREE',
  BASIC = 'BASIC',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
}

export enum AwsRegion {
  US_EAST_1 = 'us-east-1',
  US_WEST_2 = 'us-west-2',
  EU_WEST_1 = 'eu-west-1',
  EU_CENTRAL_1 = 'eu-central-1',
  AP_SOUTHEAST_1 = 'ap-southeast-1',
  AP_NORTHEAST_1 = 'ap-northeast-1',
}

export enum TenantFeature {
  CUSTOM_DOMAIN = 'CUSTOM_DOMAIN',
  SSO = 'SSO',
  API_ACCESS = 'API_ACCESS',
  ADVANCED_ANALYTICS = 'ADVANCED_ANALYTICS',
  WHITE_LABEL = 'WHITE_LABEL',
  MULTI_REGION = 'MULTI_REGION',
  CUSTOM_ROLES = 'CUSTOM_ROLES',
  AUDIT_LOGS = 'AUDIT_LOGS',
}

export enum TenantAuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  SUSPENDED = 'SUSPENDED',
  ACTIVATED = 'ACTIVATED',
  DELETED = 'DELETED',
  TIER_CHANGED = 'TIER_CHANGED',
  FEATURE_TOGGLED = 'FEATURE_TOGGLED',
  AWS_RESOURCES_PROVISIONED = 'AWS_RESOURCES_PROVISIONED',
  AWS_RESOURCES_DEPROVISIONED = 'AWS_RESOURCES_DEPROVISIONED',
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_RESTORED = 'BACKUP_RESTORED',
  QUOTA_CHANGED = 'QUOTA_CHANGED',
  CONFIG_CHANGED = 'CONFIG_CHANGED',
}
